src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @var ?Image
     *
     * @ORM\OneToOne(targetEntity="App\Entity\Image", cascade="all", orphanRemoval=true)
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private $image = null;

    /**
     * @var bool
     */
    private $deleteImage;

    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Category")
     */
    private $categories;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="events", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    /**
     * @return bool
     */
    public function getDeleteImage()
    {
        return $this->deleteImage;
    }

    public function setDeleteImage(bool $deleteImage)
    {
        $this->deleteImage = $deleteImage;
        if ($deleteImage) {
            $this->image = null;
        }

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Get the value of image.
     *
     * @return ?Image
     */
    public function getImage()
    {
        return $this->image;
    }
    
    /**
     * Set the value of image.
     *
     * @param ?Image $image
     *
     * @return self
     */
    public function setImage(?Image $image)
    {
        if (empty($image->getFile())) {
            $image = null;
        }
        $this->image = $image;

        return $this;
    }



    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setEvents($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getEvents() === $this) {
                $comment->setEvents(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

    /**
     * Get the value of categories
     *
     * @return  ArrayCollection
     */ 
    public function getCategories()
    {
        return $this->categories;
    }

    /**
     * Set the value of categories
     *
     * @param  ArrayCollection  $categories
     *
     * @return  self
     */ 
    public function setCategories(ArrayCollection $categories)
    {
        $this->categories = $categories;

        return $this;
    }
}

src/Entity/Image.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ImageRepository::class)
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $name = "";

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $path;

    /**
     * @var UploadedFile
     * 
     * @Assert\Image()
     */
    private $file;

    /**
     * @var ?string
     *
     * Chemin de l'ancien fichier en cas de modification
     */
    private $oldPath;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(UploadedFile $file)
        {
            $this->oldPath = $this->path; // Sauvegarde le chemin de l'ancien fichier pour le supprimer lors de l'upload du nouveau
            $this->path = ''; // Modifie cette valeur pour activer la modif Doctrine
            $this->file = $file;
            return $this;
        }
    

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function generatePath()
    {
        if ($this->file instanceof UploadedFile) {
            // Génére le chemin du fichier à uploader
            $this->path = uniqid('img_') . '.' . $this->file->guessExtension();
            $this->name = $this->file->getClientOriginalName();
        }
    }
    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        // Supprimer l'ancien fichier s'il existe
        if (is_file($this->getPublicRootDir() . $this->oldPath)) {
            unlink($this->getPublicRootDir() . $this->oldPath);
        }
        if ($this->file instanceof UploadedFile) {
            // Déplace le fichier uploadé var le dossier uploads
            $this->file->move(
                $this->getPublicRootDir(), // Vers le dossier public/uploads
                $this->path
            );
        }
    }
   
    
    /**
     * @ORM\PreRemove()
     */
    public function remove()
    {
        // Test si le fichier existe
        if (is_file($this->getPublicRootDir() . $this->path)) {
            unlink($this->getPublicRootDir() . $this->path); // Supprime le fichier
        }
    }
    
    /**
     * Emplacement des fichiers
     */
    public function getPublicRootDir()
    {
        return __DIR__ . '/../../public/uploads/';
    }

     /**
     * Retourne le lien pour afficher l'image (peut être inclus dans une balise img).
     */
    public function getWebPath()
    {
        return '/uploads/images/'.$this->path;
    }

    public function __toString()
    {
        return $this->name;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Event;
use App\Entity\Image;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('content')
            ->add('created_at')
            // Inclus le formulaire d'image dans le formulaire article
            ->add('image', ImageType::class, ['label' => false])
            ->add('deleteImage', CheckboxType::class, [
                'label' => 'event.delete_image',
                'required' => false, // Pas obligatoire
            ])
            ->add('categories', EntityType::class, [
                'label' => 'article.categories',
                'class' => Category::class,
                'multiple' => false,
                'expanded' => true,
                'query_builder' => function (EntityRepository $er) {
                    // Modifie la requête d'affichage de la liste des catégories
                    return $er->createQueryBuilder('c')
                        ->orderBy('c.title', 'asc')
                    ;
                },
            ])
            
            // Ajout du submit
            ->add('save', SubmitType::class, ['label' => 'save']); 
        
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use App\Repository\EventRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;


/**
 * @Route("/event")
 */
class EventController extends AbstractController
{
    /**
     * @Route("/", name="event_index", methods={"GET"})
     */
    public function index(EventRepository $eventRepository): Response
    {
        return $this->render('event/index.html.twig', [
            'events' => $eventRepository->findAll(),
        ]);
    }

    /**
     * Seul ROLE_ADMIN peut accéder à new
     * @Route("/new", name="event_new", methods={"GET","POST"})
     * @Security("is_granted('ROLE_ADMIN')")
     */
    public function new(Request $request): Response
    {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('event_index');
        }

        return $this->render('event/new.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="event_show", methods={"GET"})
     */
    public function show(Event $event): Response
    {
        return $this->render('event/show.html.twig', [
            'event' => $event,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="event_edit", methods={"GET","POST"})
     * Seul ROLE_ADMIN peut accéder à edit
     * @Route("/{id}/edit", name="event_edit", methods={"GET","POST"})
     * @Security("is_granted('ROLE_ADMIN')")
     */
    public function edit(Request $request, Event $event): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('event_index');
        }

        return $this->render('event/edit.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Seul ROLE_ADMIN peut accéder à edit
     * @Route("/{id}", name="event_delete", methods={"DELETE"})
     * @Security("is_granted('ROLE_ADMIN')")
     */
    public function delete(Request $request, Event $event): Response
    {
        if ($this->isCsrfTokenValid('delete'.$event->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('event_index');
    }
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn">Delete</button>
</form>

templates/event/_form.html.twig
{{ form_start(form) }}
    {{ form_errors(form) }} {# Affiche les eventuelles erreurs #}
        {{ form_row(form.title) }}
        {{ form_row(form.categories) }}
        {{ form_row(form.content) }}
        <div class="media mb-3">
            {% if event is defined and event.image is not empty %}
            {# asset permet de pointer sur le dossier 'public', twig appelle la méthode 'getWebPath' de l'image #}
            <img src="{{ asset(event.image.webPath) }}" class="align-left-center mr-3" style="max-width:180px"/>
            {% endif %}
            <div class="media-body">
                {{ form_row(form.image) }}
                {{ form_row(form.deleteImage) }}
            </div>
        </div>
        {{ form_row(form.created_at)}}

        {{ form_row(form.save) }}
    
{{ form_end(form) }}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Event{% endblock %}

{% block body %}
    <h1>Edit Event</h1>

    {{ include('event/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('event_index') }}">back to list</a>

    {{ include('event/_delete_form.html.twig') }}
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event index{% endblock %}

{% block body %}
    <h1>Event index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Content</th>
                <th>Created_at</th>
                <th>Image</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for event in events %}
            <tr>
                <td>{{ event.id }}</td>
                <td>{{ event.title }}</td>
                <td>{{ event.content }}</td>
                <td>{{ event.createdAt ? event.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ event.image }}</td>
                <td>
                    <a href="{{ path('event_show', {'id': event.id}) }}">show</a>
                    <a href="{{ path('event_edit', {'id': event.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('event_new') }}">Create new</a>
{% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Event{% endblock %}

{% block body %}
    <div class="container">
    <h1>Create new Event</h1>

    {{ include('event/_form.html.twig') }}

    <a href="{{ path('event_index') }}">back to list</a>
    </div>
{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}
    <h1>Event</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ event.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ event.title }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ event.content }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ event.createdAt ? event.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ event.image }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('event_index') }}">back to list</a>

    <a href="{{ path('event_edit', {'id': event.id}) }}">edit</a>

    {{ include('event/_delete_form.html.twig') }}
{% endblock %}